---
title: "Age-of-Onset (Survival): Quick Description"
output: html_document
---

The phenotype of interest, $A$, is the continuous age-of-onset for a disease, measured for $N$ unrelated individuals. We assume age-of-onset is drawn from the parametric Weibull distribution with a fixed shape parameter, $k \in \{1,2,3\}$ and the slope parameter based on the continuous liability of developing the disease (see *Continuous Liability*), Weibull$(k,l)$.

We assume that everyone would develop the disease eventually (time $\rightarrow \infty$), but that within a finite time frame (e.g. before the age at interviewing), a subset of individuals will not develop the disease. These individuals will be considered censored. The censoring is such that the proportion of cases reflects an expected population prevalence of the disease $K$. We will use the dichotomous variable $Y$ to denote whether a person developed the disease ($y=1$) or was censored ($y=0$).

For individuals who develop the disease $A$ represents their age-of-onset scaled to fall within the minimum and maximum age range. For individuals who are censored their age equals the maximum age.