---
title: "Fully Observed Case-Control: Detailed Description"
output: html_document
---

Let $Y$ be a dichotomous phenotype measured for $N$ unrelated individuals where $y=1$ indicates an individual is a carrier/case and $y=0$ indicates they are a control/non-carrier. While the actualized trait is an indicator of disease status, we assume a continuous liability $l$ of developing the trait with carrier status occurring when the liability exceeds a threshold $T$, $l \ge T$. The liability follows the standard normal distribution and is composed of two independent components, $l = l_g + l_e$.

The genetic component, $l_g$, follows the Gaussian distribution:

\begin{align}
  l_g \sim N(0, h^2)
\end{align}

while the environmental component $l_e$ follows the Gaussian:

\begin{align}
  l_e \sim N(0, 1-h^2)
\end{align}

In both distributions, $h^2$ represents the additive heritability. 

Let $K$ denote the population prevalence of the phenotype $Y$ from which we can derive the liability threshold 

\begin{align}
T = \Phi^{-1}(1-K)
\end{align}

From this generative model, we assume that only the liability of developing the disease is heritable. For individuals who develop the disease, the age-of-onset follows the truncated Gaussian with the minimum and maximum age representing $\Phi^{-1}(0.025)$ and $\Phi^{-1}(0.975)$, respectively. 

For individuals who do not develop the disease, only the censoring age is observed (e.g. the date interviewed). The age of censoring also follows a truncated Gaussian with the minimum and maximum representing $\Phi^{-1}(0.025)$ and $\Phi^{-1}(0.975)$, respectively. It is assumed that the age of onset and censoring ages are drawn independently from the liability conditionally on the case-control status. While all patients were interviewed (i.e. everyone experiences the censoring event), it is assumed that all cases/carriers have an age-of-onset that precedes the censoring age. We relax this assumption in *Partially Observed Case-Control Status*.

We note that instead of directly generating the genetic liability $l_g$ from the normal distribution (shown above), we observe the standardized genotype matrix $X$ containing $M$ SNPs. We assume there are $C \subseteq M$ causal SNPs whose effect sizes, $\beta$ are drown according to the polygenic model:

\begin{align}
\beta \sim N(0, \frac{h^2}{M})
\end{align}
