---
title: "Fully Observed Case-Control: Detailed Description"
output: html_document
---

Let $Y$ be a dichotomous phenotype measured for $N$ unrelated individuals where $y=1$ indicates an individual is a carrier/case and $y=0$ indicates they are a control/non-carrier. While the actualized trait is an indicator of disease status, we assume a continuous liability $l$ of developing the trait with carrier status occurring when the liability exceeds a threshold $T$, $l \ge T$. The liability follows the standard normal distribution and is composed of two independent components, $l = l_g + l_e$.

The genetic component, $l_g$, follows the Gaussian distribution:

\begin{align}
  l_g \sim N(0, h^2)
\end{align}

while the environmental component $l_e$ follows the Gaussian:

\begin{align}
  l_e \sim N(0, 1-h^2)
\end{align}

In both distributions, $h^2$ represents the additive SNP-heritability. 

Let $K$ denote the population prevalence of the phenotype $Y$ from which we can derive the liability threshold 

\begin{align}
T = \Phi^{-1}(1-K)
\end{align}

We note that the sample prevalence of cases, $P$, does not always equal the population prevalence. For simplicity, we will assume the sample prevalence is either 50\% or equals the population prevalence.

From this generative model, we begin with the assumption that only the liability of developing the disease is heritable; therefore, the age-of-onset, $A$, is drawn from truncated Gaussian with the minimum and maximum age representing the quantiles: $\Phi^{-1}(0.025)$ and $\Phi^{-1}(0.975)$, respectively. 

We relax this assumption and instead draw the age-of-onset, $A$, from a logistic function of the liability, $l$ and population prevalence, $K$:

\begin{align}
-ln(\frac{K}{(1-\Phi(l))} - 1)
\end{align}

The distribution is then scaled such that the age-of-onsets falls within the minimum and maximum age.

For individuals who do not develop the disease, only the censoring age is observed (e.g. the date interviewed). The age of censoring also follows a truncated Gaussian with the minimum and maximum representing $\Phi^{-1}(0.025)$ and $\Phi^{-1}(0.975)$, respectively. 

We assume all cases/carriers are observed which is to say they have an age-of-onset that precedes the censoring age. This assumption is relaxed in *Partially Observed Case-Control Status*.

We note that instead of directly generating the genetic liability $l_g$ from the normal distribution (shown above), we observe the standardized genotype matrix $X$ containing $M$ independent SNPs. We assume that the minor allele frequency (MAF) $> 0.05$ or such that the minor allele count is 25, whichever is greater. We assume there are $C \subseteq M$ causal SNPs whose effect sizes, $\beta$ are drown according to the polygenic model:

\begin{align}
\beta \sim N(0, \frac{h^2}{M})
\end{align}
